name: Continuous Integration

on: [push, pull_request]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Codecov
      uses: codecov/codecov-action@v3
      # env:
      #   CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      # with:
      #   files: ./coverage/lcov.info
      #   fail_ci_if_error: false
